import { Inter } from "next/font/google";
import "./globals.css";

import SecondList from "./uslugi/page";
import ThirdList from "./o-nas/page";
import FourthList from "./novosti/page";
import Footer from "./component/footer/footer";
import NewPage from "./component/NewPage/NewPage";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div >
          <NewPage/>
        </div>
        {children}
        <div >
          <ThirdList/>
        </div>
        <div>
          <FourthList/>
        </div>
        <div >
          <Footer/>
        </div>
        </body>
    </html>
  );
}
